### ISSUE TITLE
Bigger windows to see better the file names in linux.

### ISSUE THREAD

**Issue by MandiYang** [demosthenesk/ClamGuard#2]
I need bigger window to see the file name or the folder name better because the file name of some folder names are ...

**Comment by MandiYang** [comment]
![Screenshot from 2021-06-27 20-11-24](https://user-images.githubusercontent.com/64307609/123555150-346ac700-d784-11eb-9bfc-81686c6586c8.png)

**Comment by MandiYang** [comment]
![Screenshot from 2021-06-27 20-11-24](https://user-images.githubusercontent.com/64307609/123555242-cd014700-d784-11eb-8f23-7f276ca5961e.png)

**Comment by demosthenesk** [comment]
First column width and sort order are now fixed.
Thanks for feedback!
